### ISSUE TITLE
Android Studio Theme

### ISSUE THREAD

**Issue by msal4** [raxityo/KotlinPlayground#1]
Hey Raxit, Can you place name the theme you're using for Android Studio or how you accomplished this look?

Thanks!

**Comment by raxityo** [comment]
Hey @msal4,
I am using [Material Theme UI](https://plugins.jetbrains.com/plugin/8006-material-theme-ui) plugin for JetBrains. The theme of the IDE is Oceanic. The color scheme is Monokai.

I wrote about how I accomplished the look of the overall IDE to hide toolbars and panels here: https://medium.com/@rax/distraction-free-development-in-android-studio-f117b20493d2. 🙂 

Cheers,
Rax
